### ISSUE TITLE
关于部署的一个疑问

### ISSUE THREAD

**Issue by LanYunDev** [wejectchen/ginblog#10]
在第5步:在database中将sql文件导入数据库,推荐navicat或者其他sql管理工具导入
不太清楚具体如何操作
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/95263282/167231356-cae07af9-a497-415b-a2a2-dc0fd8da6f97.png">

**Comment by wejectchen** [comment]
Navicat有个执行sql文件，直接运行data目录下sql文件即可。

**Comment by LanYunDev** [comment]
对于Navicat的操作，我仍然存在不明白的地方，还请能详细说一下
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/95263282/167247943-82b3c928-572e-4ffe-a1f5-0c8e0cf4e2ee.png">

**Comment by wejectchen** [comment]
你这个是没连接到数据库，还谈不上执行数据库文件的问题。

**Comment by LanYunDev** [comment]
所以如何从0开始设置或配置才能到执行数据库文件这一步呢

**Comment by wejectchen** [comment]
这个可以搜索下navicat的教程，操作挺简单的
