### ISSUE TITLE
刷新文章页面提示404

### ISSUE THREAD

**Issue by dzhl** [wejectchen/ginblog#11]
打开文章后，然后刷新浏览器，跳转到页面，显示404

**Comment by wejectchen** [comment]
这个需要结合vue-router重定向进行处理。
具体可以参照vue-router的配置文档：[https://v3.router.vuejs.org/zh/guide/essentials/history-mode.html#%E5%90%8E%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%BE%8B%E5%AD%90](https://v3.router.vuejs.org/zh/guide/essentials/history-mode.html#%E5%90%8E%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%BE%8B%E5%AD%90)
