### ISSUE TITLE
不能直接修改配置中的端口

### ISSUE THREAD

**Issue by Totn** [wejectchen/ginblog#14]
前端打包好的文件里的后端地址是写死的"localhost:3000",
这导致修改后端接口后程序不能正常访问和使用；
并且在非本地部署的情况下, "localhost"也使得前端访问不到后端的API

建议: 在`readme.md`文件中加入打包前端文件的步骤说明, 方便后端程序员自己修改地址和端口

**Comment by wejectchen** [comment]
readme好像写的吧，我看看呢。

**Comment by wejectchen** [comment]
写了的，在docker部署那部分里面。
