### ISSUE TITLE
评论后无法显示

### ISSUE THREAD

**Issue by okatu-loli** [wejectchen/ginblog#15]
如图，提交评论后在数据库可以看到评论，但在前台无法看见评论
![image](https://github.com/wejectchen/Ginblog/assets/53247097/5650ed8f-4a15-4096-a2eb-1879ff2257b3)
![image](https://github.com/wejectchen/Ginblog/assets/53247097/a7302cce-0fd5-49bd-abe6-f8af78aa238d)

**Comment by wejectchen** [comment]
为防止灌水机器人、垃圾广告，后台增加了审核功能，审核通过了才能显示，你可以查看下后台管理页面。

当然，你也可以接入第三方审查接口对评论内容进行审查。
