### ISSUE TITLE
博客页右上角文章搜索功能有bug

### ISSUE THREAD

**Issue by dfaofeng** [wejectchen/ginblog#2]
测试了下,只能搜索文章前几个字才搜的到,例如:服务器部署流程 搜索服务器 可以搜到,但是直接送服务 就提示没有文章,还有那个文章图片上传的地方也有bug
![QQ截图20210115044844](https://user-images.githubusercontent.com/14891398/104847424-dc00e500-591a-11eb-8e54-d1e93bb2c70c.png),那个缩略图上传触发也有bug,点过一次后,取消,再上传后,还是提示没上传

**Comment by wejectchen** [comment]
非常感谢反馈。
1. 关于搜索，我在https://www.bilibili.com/video/BV19V411U7ud 这个视频中有所介绍，对于模糊查询这块，这里使用的是 `%key` 如果你要全局模糊搜索，可以使用 `%key%`这种模式。
2. 上传图片这里我这边测试是没问题的，能否提供进一步信息。
thanks～

**Comment by dfaofeng** [comment]
我这波用%key%处理好了,图片我这边测试了下,又没问题了..我这边把后端的返回的值用反射的方式获取,现在正在改admin的代码,改好了我就pull过来

**Comment by wejectchen** [comment]
非常感谢～
如果没其他问题，此issue暂时关闭。
