### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by LiMoMoMo** [wejectchen/ginblog#4]
1. 网关处关闭3000端口访问的转发。
2. 接口添加权限校验。尤其是修改密码的接口，不然，普通用户可以通过id改其他用户的密码，这不是很奇怪吗？😂😂😂

**Comment by wejectchen** [comment]
收到，感谢提出建议，我抽空看看。

**Comment by wejectchen** [comment]
我看了看，目前的策略是只有管理员才能修改密码，普通用户不能修改密码，对于个人博客（非多用户）来说，这是应该没什么问题的，你这边能帮我测试吗？`普通用户可以通过id改其他用户的密码` 应该是不被允许的。
