### ISSUE TITLE
这部分的逻辑在更改密码的模型中存在二次的加密运算

### ISSUE THREAD

**Issue by TrueAbc** [wejectchen/ginblog#5]
https://github.com/wejectchen/Ginblog/blob/a7c023dcb240c79769f8aeafc1b9cec4dec8efef/model/User.go#L120-L129

![image](https://user-images.githubusercontent.com/47651330/110930547-33905f80-8364-11eb-8d33-53c0bf3f163f.png)

**Comment by wejectchen** [comment]
感谢关注与反馈。我稍后看看～

**Comment by wejectchen** [comment]
fixed. 
details:[https://github.com/wejectchen/Ginblog/commit/f23afa3a2e28202e20738a4b1408b6bb3031e366](https://github.com/wejectchen/Ginblog/commit/f23afa3a2e28202e20738a4b1408b6bb3031e366)
