### ISSUE TITLE
article和category的连表查询问题

### ISSUE THREAD

**Issue by TrueAbc** [wejectchen/ginblog#6]
https://github.com/wejectchen/Ginblog/blob/37d808a0187f76677d840e48af960bff77157833/model/Article.go#L71-L75

这里的Joins逻辑是不是需要写join的sql，我直接按着作者这个写法来生成的sql 无法正常执行，

不知道为啥图片传不上来, 
我把查询改成这样了
``` go
err = db.Select("articles.id,title, img, created_at, updated_at, `desc`, " +
		"categories.name").
		Limit(pageSize).Offset((pageNum-1)*pageSize).
		Order("Created_At DESC").Where("title LIKE ?",
		title+"%",
	).Joins("inner join categories on categories.id = articles.cid").Find(&articleList).Count(&total).Error
```

想问下是不是gorm版本问题

**Comment by wejectchen** [comment]
hi,欢迎反馈，能复现下结果和提供下gorm的loginfo么？
我不确定是不是gorm的问题

**Comment by TrueAbc** [comment]
最近学校比较忙，然后还把环境再另一台电脑上重新搭建了下。。。。

这个是报错的结果（我构建表的时候没有去除复数形式）
![image](https://user-images.githubusercontent.com/47651330/111890748-7ff43300-8a27-11eb-936a-1014aeb2a16e.png)

然后这是生成的sql, 可以看到时没有join的相关信息的，直接放到datagrip中执行也会报错（其实生成的sql的from两个表之间加个“，”可以执行，但是很明显逻辑不对）
```sql
SELECT articles.id,title, img, created_at, updated_at, `desc`, categories.name FROM `articles` categories WHERE title LIKE 'ad%' AND `articles`.`deleted_at` IS NULL ORDER BY Created_At DESC LIMIT 5
```
gorm版本v1.20.12

**Comment by wejectchen** [comment]
gorm v2对逻辑关系的处理貌似有点变化。
参考以下形式。

```golang
// `User` 属于 `Company`，`CompanyID` 是外键
type User struct {
  gorm.Model
  Name      string
  CompanyID int
  Company   Company
}

type Company struct {
  ID   int
  Name string
}
```

**Comment by TrueAbc** [comment]
刚才看了一下，v2的版本确实joins的写法确实应该是作者这样，之前一直看的都是1.x的文档
