### ISSUE TITLE
想问下这什么问题

### ISSUE THREAD

**Issue by softwarebuy** [wejectchen/ginblog#9]
![image](https://user-images.githubusercontent.com/68842519/143445465-da415021-c216-4b4b-9197-5ce5bd160618.jpeg)

怎么会localhost提交
我已经放腾讯云windows服务器上
并且有域名

**Comment by wejectchen** [comment]
readme有说明，这里需要修改下前端的请求地址，并重新打包

**Comment by wejectchen** [comment]
最后我们在确定下前端 web 文件夹下的axios请求地址
// 在 web/admin/src/plugin/http.js 和 web/front/src/plugin/http.js 两个文件夹中,将 baseURL地址改为部署的服务器线上地址

axios.defaults.baseURL = 'http://localhost:3000/api/v1'

// 修改为

axios.defaults.baseURL = 'http://线上服务器ip或域名:3000/api/v1'
别忘了，修改完地址后，重新打包下

$ yarn build

$ npm run build

**Comment by HappyUniversity** [comment]
axios.defaults.baseURL默认相对路径直接拼接，如果要在前端使用axios连接其他url的后端程序，可以直接写"http//..............."这样的绝对路径，axios.defaults.baseURL就失效了！
